Pull translations from Transifex
justarrived/just-match-web pull request #13
Opened 2016-10-08 14:59 UTC by buren

2016-10-12 12:11 UTC, belev requested changes
Can you fix the indentations to be with two spaces so that we can merge the pull request?

2016-10-12 21:03 UTC, buren commented
@Belev the content is pulled using the official Transifex client (with `tx pull -a -f`). 

So then we'd need to fix the indentation every time we pull new translations..

2016-10-13 07:44 UTC, Belev commented
Yes, unfortunately. But we use two spaces in the whole project so it will be good to indent the translation files correctly. Isn't there any shortcut to reindent the file using the project settings?

2016-10-25 12:46 UTC, belev approved these changes

2016-10-25 12:47 UTC, merged