Added error message to job confirm call
justarrived/just-match-web pull request #300
Opened 2017-02-15 11:21 UTC by Ekman1991

2017-02-15 11:23 UTC, Ekman1991 commented
Generic error message for now. This needs further work.

- [ ] Implement correct error message (taken from the API?)

2017-02-15 19:44 UTC, buren commented on src/app/views/job-details/job-details.component.html
> +        <h3 *ngIf="applyForJobErrorMessageVisible">An error occured when providing answer to this job.</h3>
Move string to `src/assets/i18n/en.yml` 😄

2017-02-15 19:44 UTC, buren commented on src/app/views/job-details/job-details.component.ts
> +  private applyForJobErrorMessageVisible: boolean = false;
🙇 for typing

2017-02-21 19:47 UTC, buren requested changes
Can't merge before hardcoded string is moved to `en.json` :)

2017-02-22 14:14 UTC, bellevik approved these changes

2017-02-23 13:51 UTC, buren commented
A lot better than we have now (which is nothing 😉), however going forward I think we can just rely on the API to provide validations & error messages.

2017-02-23 13:51 UTC, buren approved these changes

2017-02-23 13:51 UTC, buren commented on src/assets/i18n/en.json
> +  "assignment.status.confirmation_error" : "An error occured when providing answer to this job.",
Can't we use the error message from the API?

2017-02-23 13:51 UTC, buren commented on src/assets/i18n/en.json
> +  "assignment.status.confirmation_error" : "An error occured when providing answer to this job.",
Better than we have now, so "letting" this go...

2017-02-23 13:51 UTC, merged