Add gender to edit profile page closes #305
justarrived/just-match-web pull request #372
Opened 2017-03-03 15:11 UTC by Ekman1991

2017-03-03 15:12 UTC, buren commented
I like it 👍 Perhaps we should extract this to its own component `<user-gender-select>` or sth like that while we're at it.

2017-03-03 15:16 UTC, Ekman1991 commented
Is it not better to keep the implementation of `<user-gender-select>` in https://github.com/justarrived/just-match-web/pull/370 ?

2017-03-04 13:06 UTC, bex1 requested changes
Good 👍 Just fix my two comments then merge

2017-03-04 13:06 UTC, bex1 commented on src/app/components/forms/user-details-form/user-details-form.component.ts
> +  private genders: Promise<UserGender[]>;
SHould be public

2017-03-04 13:06 UTC, bex1 commented on src/app/components/forms/user-details-form/user-details-form.component.ts
> +  loadData() {
Extend TranslationsListener. See conventions please.
Its not enough to just add loadData function.

2017-03-05 13:02 UTC, bex1 approved these changes

2017-03-13 03:26 UTC, bex1 commented
This will not be merged. Solved in #386 instead

2017-03-13 03:26 UTC, closed without merging